import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getSession, SessionProvider } from "next-auth/react";
import Providers from "@/context/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
const session = await getSession ()

  return (
    
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Providers session={session}>
        {children}
        </Providers>
      </body>
    </html>
    
  );
}
