import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/context/Providers";
// import { getSession } from "@/utils/authOptions";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const session = await getSession()

  // console.log("session:", session)

  return (

    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>         
        <main style={{ marginTop: '100px', marginLeft: '250px' }}>
          {/* <Providers session={session}> */}
            {children}
          {/* </Providers> */}
        </main>
      </body>
    </html>

  );
}
